src/index.css

- Cursor AI의 도움으로 아래와 같은 구조로 프로젝트 세팅을 완료했습니다.
- 프로젝트 구축
- cursor ai 프롬프트에 입력 후 명령어 실행
- Close #2 
- See also #
- 프로젝트 구조와 상태관리 개념에 대해 학습해두면 ai 활용에 큰 도움이 될 것 같습니다.

chore: 프로젝트 초기 세팅 (#2)

---

package-lock.json
package.json
postcss.config.cjs
src/components/CompanyEditModal.tsx
src/features/company/components/CompanyEditModal/CompanyEditModal.tsx
src/index.css

develop clone시 실행 안되던 현상 수정 styled-components 적용
styled-components 의존성 추가
- Close #11 
local환경에서 npm run dev로 확인

[Fix] develop clone시 실행 안되던 현상 수정 styled-components 적용

---

src/contexts/AuthContexts.tsx
src/layouts/Header/ProfileDropdown.tsx
src/layouts/Header/UserProfile.styled.ts
src/layouts/Header/UserProfile.tsx
src/layouts/Sidebar/Sidebar.styles.ts
src/layouts/Sidebar/Sidebar.tsx

- 하드코딩된 유저 정보를 실제 정보로 수정했습니다.
- 유저 정보 디자인을 수정했습니다.
- 실제 유저 정보를 받아와서 contexts로 관리합니다.
- Close #23 
- See also #

[Feature] 실제 정보 조회 및 디자인

---

src/features/auth/pages/LoginPage.tsx
vite.config.ts

- 설정 수정
- axios 설정 변경
- Close #
- See also #
- 헤더 값을 읽지 못 해서 Cors 설정 수정 해야 됩니다..

[Feature] 로그인 시 axios 사용으로 수정

---

src/App.tsx
vite.config.ts

- 불필요한 코드 삭제
- Close 
- See also #16

[Refactor] 오류 수정

---

vercel.json

[Fix] 버그 수정 

---

src/App.styled.ts
src/App.tsx
src/features/admin/pages/DashboardPage.styled.ts
src/layouts/Footer/Footer.styled.ts

- #29  이슈를 참고하여 푸터 하단 고정으로 변경
- 각 페이지 styles의 Container에 [min-height=100vh] 설정하여 전체 높이 설정
- Close #68 
- See also #29 
- 변경 전
- 변경 후
- 레이아웃에서 MainContent가 flex, `flex-direction: column`이므로 flex: 1, min-height=100vh 이 있어야 하단 푸터와 자연스럽게 맞닿습니다.

[Feature] 푸터 하단 고정

---

src/App.tsx
src/features/project/pages/CompletedProject.tsx
src/features/project/pages/CreateProjectPage.tsx
src/features/project/pages/EditProjectPage.tsx
src/features/project/pages/InProgressProject.tsx
src/features/project/pages/ProjectDetailPage.styled.ts
src/features/project/pages/ProjectDetailPage.tsx
src/features/project/pages/UserProjectPage.tsx
src/layouts/Sidebar/Sidebar.tsx

프로젝트 수정 페이지 및 단계 승인자, 승인상태 변경
- 프로젝트 수정 페이지 input 기존 프로젝트 정보로 세팅
- 단계 승인자 변경
- 단계 생성, 수정, 삭제 api 연동
- 승인자가 승인상태 변경 ( 거절 / 승인 )
- Close #
- See also #
프로젝트 수정 페이지의 개발사, 고객사 담당자 input은 be와 값이 안맞아서 be 수정 후에 다시 올리겠습니다.

[Feature] 프로젝트 수정 페이지 및 단계 승인자, 승인상태 변경

---

src/hooks/useNotification.ts
src/layouts/Header/NotificationDropdown.tsx

[Feature] 알림 서비스 수정

---

src/features/admin/pages/DashboardPage.tsx
src/hooks/useNotification.ts

[Fix] 초기값 세팅이 안되어 화면 렌더링이 안되는 오류 수정

---

src/index.css

- 폰트 변경
- 기존 폰트
- 새로운 폰트
- Close #87 
- See also #

design: 전체 폰트 변경 (#87)

---

src/features/project-d/pages/AdminProjectPage.styled.ts
src/features/project-d/pages/ProjectDetailPage.styled.ts
src/features/project-d/pages/ProjectDetailPage.tsx
src/features/project/components/Board/ProjectBoard.styled.ts
src/features/project/components/Board/ProjectBoard.tsx
src/features/project/components/Card/ProjectCard.styled.ts
src/features/project/components/Card/ProjectCard.tsx
src/features/project/components/Header/ProjectHeader.styled.ts
src/features/project/components/Header/ProjectHeader.tsx
src/features/project/components/List/ProjectFilterBar.styled.ts
src/features/project/components/List/ProjectFilterBar.tsx
src/features/project/components/Progress/ProjectProgress.styled.ts
src/features/project/components/Progress/ProjectProgress.tsx
src/features/project/pages/ProjectDetailPage.tsx
src/features/project/pages/ProjectListPage.styled.ts
src/features/project/pages/ProjectListPage.tsx
src/layouts/Sidebar/Sidebar.tsx

프로젝트 목록, 프로젝트 상태, 게시글 목록 ui 개편
프로젝트 목록 화면 변경
프로젝트 상세 화면 변경
게시글 목록은 프로젝트 상태 하단 단계에 의한 렌더링으로 변경
- Close #92 
- See also #

[Style] 프로젝트 목록, 프로젝트 상태, 게시글 목록 ui 개편

---

src/features/board/components/Comment/components/CommentItem.tsx
src/features/board/components/Post/components/DetailModal/ProjectPostDetailModal.tsx
src/features/board/components/Post/components/FormModal/PostFormModal.tsx
src/features/board/components/Post/components/FormModal/components/PostFormActions.tsx
src/features/board/components/Post/components/FormModal/components/PostFormFields.tsx
src/features/board/components/Post/pages/PostListPage.tsx
src/features/board/components/Post/styles/PostFormModal.styled.ts
src/features/board/components/Post/styles/PostListPage.styled.ts
src/features/board/components/Post/styles/ProjectPostDetailModal.styled.ts
src/features/company/components/CompanyFilterBar.tsx
src/features/project-d/services/postService.ts
src/features/project-d/types/post.ts
src/features/project/components/Board/ProjectBoard.styled.ts
src/features/project/components/Board/ProjectBoard.tsx
src/features/project/components/Header/ProjectHeader.tsx
src/features/project/components/Progress/ProjectProgress.styled.ts
src/features/project/components/Progress/ProjectProgress.tsx
src/features/project/pages/ProjectDetailPage.tsx
src/features/project/pages/ProjectListPage.tsx
src/features/project/services/commentService.ts
src/features/project/services/projectService.ts
src/features/project/types/Types.ts

프로젝트(일부), 게시글 api 연동 및 ui 수정
- Close #102 
- Close #103 
- See also #
- 페이지네이션 문제가 있음. 멘토링 질의 준비 중

[Feature] 프로젝트(일부), 게시글 api 연동 및 ui 수정

---

src/components/ClickableMentionedUsername.tsx
src/components/MentionSuggestions.tsx
src/components/MentionTextArea.tsx
src/components/UserProfileDropdown.tsx
src/features/board/components/Answer/hooks/useAnswerUtils.tsx
src/features/board/components/Answer/pages/AnswerDetailModal.tsx
src/features/board/components/Comment/hooks/useCommentUtils.tsx
src/features/board/components/Comment/styles/CommentActions.styled.ts
src/features/board/components/Post/components/DetailModal/CommentForm.tsx
src/features/board/components/Post/components/DetailModal/CommentItem.tsx
src/features/board/components/Post/components/DetailModal/CommentSection.tsx
src/features/board/components/Post/components/DetailModal/PostAttachments.tsx
src/features/board/components/Post/components/DetailModal/PostContent.tsx
src/features/board/components/Post/components/DetailModal/PostHeader.tsx
src/features/board/components/Post/components/DetailModal/ProjectPostDetailModal.tsx
src/features/board/components/Post/components/DetailModal/ReplyItem.tsx
src/features/board/components/Post/components/FormModal/PostFormModal.tsx
src/features/board/components/Post/styles/ProjectPostDetailModal.styled.ts
src/features/board/pages/DashboardPage.tsx
src/features/project-d/pages/CreateProjectPage.tsx
src/features/project-d/pages/EditProjectPage.tsx
src/features/project-d/types/question.ts
src/features/project/components/Board/ProjectBoard.tsx
src/features/project/services/projectService.ts
src/features/project/types/Types.ts
src/features/user/components/MemberRegisterModal/MemberRegisterModal.tsx
src/hooks/useMention.ts
src/routes/AppRoutes.tsx
src/utils/errorHandler.ts
src/utils/mentionUtils.tsx

- getInitials 함수에서 undefined username 처리 추가  
- PostDetailModal에서 UserProfileDropdown props 전달 방식 개선  
- profileState 대신 개별 props 전달  
- 모달 ESC/외부 클릭 닫기 기능 복원 및 애니메이션 적용  
- 헤더 버튼 간격 및 텍스트 개선, 수정일 표시 추가  
- PostHeader 및 ModalHeader 레이아웃 개선  
- Close #
- See also #

[Hotfix] 게시글 관련 오류 수정, 컴포넌트 분리, user role에 따른 라우팅 경로 추가

---

package-lock.json
package.json
src/features/admin/pages/DashboardPage.tsx
src/features/company/components/CompanyEditModal/CompanyEditModal.tsx
src/features/company/components/CompanyRegisterModal/CompanyRegisterModal.tsx
src/features/company/pages/CompanyPage.tsx

회사 수정 시 중복 확인 및 유효성검사 기능 구현
회사 수정 시 중복 확인 및 유효성검사 기능 구현
- Close #112
로컬 환경에서의 테스트 결과 정상 동작

[Feature] 회사 수정 시 중복 확인 및 유효성검사 기능 구현

---

src/layouts/Sidebar/MenuItem.styled.ts
src/layouts/Sidebar/MenuItem.tsx
src/layouts/Sidebar/Sidebar.styles.ts

- 사이드바 디자인 변경
- 사이드바 디자인 변경
- 기존
- 새로운 디자인
- Close #117 
- See also #97

[Feature] 사이드바 디자인 변경 

---

src/features/project/pages/ProjectListPage.tsx
src/features/project/services/projectService.ts

- 프로젝트 생성 모달 추가
- 프로젝트 생성 모달 구현
- api 연결
- 진행률 필드 추가
- Close #
- See also #
- UI 스타일은 변경 예정입니다.

[Feature] 프로젝트 생성 모달 추가(#98)

---

src/features/board/components/Post/components/DetailModal/PostHeader.tsx
src/features/board/components/Post/components/DetailModal/ProjectPostDetailModal.tsx
src/features/board/components/Post/components/FormModal/PostFormModal.tsx
src/features/board/components/Post/components/FormModal/components/PostFormFields.tsx
src/features/board/components/Post/pages/PostListPage.tsx
src/features/project-d/services/postService.ts
src/features/project-d/types/post.ts
src/features/project/components/Board/ProjectBoard.styled.ts
src/features/project/components/Board/ProjectBoard.tsx

- 게시글타입이 질문이 없고 공지로 잘못 매핑돼있는 문제를 해결
- NOTICE 타입을 없애고 GENERAL, QUESTION 으로 올바르게 생성되도록 수정
- Close #
- See also #

[Hotfix] 게시글타입이 질문이 없고 공지로 잘못 매핑돼있는 문제를 해결

---

src/features/project/components/List/ProjectFilterBar.tsx
src/features/project/pages/ProjectListPage.tsx
src/features/project/services/projectService.ts

- 회사 목록 api, 유저 목록 api
- 프로젝트 생성 api 연결
- Close #
- See also #

[Feature] 프로젝트 생성 api 연결

---

src/features/company/components/CompanyEditModal/CompanyEditModal.tsx
src/features/company/components/CompanyRegisterModal/CompanyRegisterModal.tsx
src/features/company/pages/CompanyDetailPage.tsx
src/features/company/pages/CompanyPage.tsx
src/features/user/components/MemberEditModal/MemberEditModal.tsx
src/features/user/pages/MemberDetailPage.tsx
src/features/user/pages/MemberPage.tsx

회원 상세 페이지 디자인 재구성 및 회사 관리, 회원 관리 수정 삭제 버튼 이동
회원 상세 페이지 디자인 재구성 및 회사 관리, 회원 관리 수정 삭제 버튼 이동
- Close #131
로컬 환경 테스트 결과 정상 동작 확인

[Feature] 회원 상세 페이지 디자인 재구성 및 회사 관리, 회원 관리 수정 삭제 버튼 이동

---

src/features/company/components/CompanyDetailModal/CompanyDetailModal.tsx
src/features/company/components/CompanyEditModal/CompanyEditModal.tsx
src/features/user/components/MemberDetailModal/MemberDetailModal.tsx
src/features/user/components/MemberEditModal/MemberEditModal.tsx
src/features/user/components/MemberRegisterModal/MemberRegisterModal.tsx
src/features/user/pages/MemberPage.tsx

회원 클릭 시 상세 모달과 조회 api 수정
회원 클릭 시 상세 모달 나오게하고 조회 api 수정
상세 모달 내 수정, 삭제 버튼 배치 후 api 연동
- Close #155
로컬 환경 정상 동작 확인

[Feature] 회원 클릭 시 상세 모달과 조회 api 수정

---

src/features/inquiry/pages/InquiryDetailPage.tsx

문의사항 상세 페이지에서 목록으로가는 버튼 구현
문의사항 상세 페이지에서 권한에 따라 목록으로가는 버튼 구현
- Close #159
로컬 테스트 결과 정상 동작 확인

[Feature] 문의사항 상세 페이지에서 목록으로가는 버튼 구현

---

src/features/project/components/Card/ProjectCard.tsx
src/features/project/components/List/ProjectFilterBar.tsx
src/features/project/pages/ProjectDetailPage.tsx
src/features/project/pages/ProjectListPage.tsx
src/features/project/services/projectService.ts
src/features/project/types/Types.ts

프로젝트 상태 변수명 변경
- [] 기능 추가 (Feature)
- Close #
- See also #

[Refator] 프로젝트 상태 변수명 변경

---

src/features/project/components/Header/ProjectHeader.tsx
src/features/project/pages/ProjectListPage.tsx

권한별 버튼 display
- Close #
- See also #

[Feature] 권한별 버튼 display

---

src/features/project/components/Progress/ProjectProgress.styled.ts
src/features/project/components/Progress/ProjectProgress.tsx
src/features/project/components/Progress/StepOrderModal.styled.ts
src/features/project/components/Progress/StepOrderModal.tsx
src/features/project/pages/ProjectDetailPage.tsx
src/features/project/services/projectService.ts

- 프로젝트 단계 관리 기능 구현 
- 단계 추가/삭제 기능 구현
- 단계 순서 변경을 위한 드래그 앤 드롭 로직 완성
- 단계 이름 수정 기능 추가
- API 연동 (`GET`, `POST`, `PUT`, `DELETE`) 구현
- 저장 및 삭제 시 Toast 알림 처리
- 모달 외부 클릭 시 자동 닫힘 처리
- 역할이 `관리자` 또는 `개발사`일 경우에만 단계 수정 가능
- Close #156 
- See also #

[Feature] 프로젝트 단계 관리 기능 구현 

---

src/features/project/components/ProjectCreateModal.tsx
src/features/project/pages/ProjectDetailPage.tsx
src/features/project/pages/ProjectListPage.styled.ts
src/features/project/pages/ProjectListPage.tsx

금액 필드 추가 및 페이지 번호 제한
- [] 리팩토링 (Refactor)
- Close #
- See also #

[Feature] 금액 필드 추가 및 페이지 번호 제한

---

src/features/inquiry/pages/InquiryDetailPage.tsx

- 답변 완료 상태에서 유저에게(관리자X) 문의사항 수정, 삭제 버튼이 보이는 것(완료 시 보이지 않게)
- 답변 완료 상태에서 관리자가 답변 등록 UI를 볼 수 없게 수정
- DB와 글자 수 일치 (255자)
- 답변 완료 상태에서 유저에게(관리자X) 문의사항 수정, 삭제 버튼이 보이는 것(완료 시 보이지 않게)
- 답변 완료 상태에서 관리자가 답변 등록 UI를 볼 수 없게 수정
- DB와 글자 수 일치 (기존 1000자에서 255자로 수정)
- Close #168
로컬 테스트 결과 정상 동작 확인

[Feature] 문의사항 세부 수정

---

src/features/company/components/CompanyDetailModal/CompanyDetailModal.tsx
src/features/company/components/CompanyEditModal/CompanyEditModal.tsx
src/features/company/components/CompanyRegisterModal/CompanyRegisterModal.tsx
src/features/company/pages/CompanyPage.tsx

업체 등록, 수정 모달 우편번호 검색 API 추가
업체 등록, 수정 모달 우편번호 검색 API 추가
- Close #173
로컬 테스트 정상 동작 확인

[Feature] 업체 등록, 수정 모달 우편번호 검색 API 추가

---

src/features/project/components/CompanyMemberSelectModal.tsx

- 프로젝트 생성 시 업체등록 및 멤버 등록 모달 연결
- Close #
- See also #

[Feature] 프로젝트 생성 시 업체등록 및 멤버 등록 모달 연결

---

src/features/project/components/Card/ProjectCard.tsx
src/features/project/pages/ProjectListPage.tsx
src/features/project/services/projectService.ts
src/features/project/types/Types.ts
src/features/user/pages/dashboard/UserDashboardPage.tsx
src/features/user/pages/dashboard/components/ProjectStatusSection.tsx
src/features/user/pages/dashboard/components/WarningProjectsSection.tsx

- 프로젝트 조회 API 
- api 연동 
- 프로젝트 조회 제대로 가져오기
- 지연 상태 오타 수정
- Close #140 
- See also #

[Feature] 회원 대시보드 프로젝트 조회 실제 데이터 연동

---

src/routes/AppRoutes.tsx

잘못된 권한 확인
- Close #
- See also #

[Fix] 잘못된 권한 확인

---

src/features/project/components/List/ProjectFilterBar.tsx
src/features/project/pages/ProjectListPage.tsx

- enum 변수명 변경
- Close #
- See also #

[Fix] status enum 변수명 변경

---

src/features/admin/components/ActivityLogDetailModal.tsx
src/features/admin/pages/ActivityLogPage.tsx
src/features/board/components/Post/components/DetailModal/PostAttachments.tsx
src/features/board/components/Post/components/DetailModal/ProjectPostDetailModal.tsx
src/features/board/components/Post/components/FormModal/PostFormModal.tsx
src/features/company/pages/CompanyPage.tsx
src/features/inquiry/InquiryPage.tsx
src/features/inquiry/UserInquiryPage.tsx
src/features/project-d/pages/ProjectPostPage.tsx
src/features/project-d/services/postService.ts
src/features/project-d/types/post.ts
src/features/project/components/Board/ProjectBoard.tsx
src/features/project/components/Board/ProjectBoardPagination.tsx
src/features/project/components/ProjectCreateModal.tsx
src/features/project/pages/ProjectDetailPage.tsx
src/features/project/pages/ProjectListPage.tsx
src/features/project/services/projectService.ts
src/features/project/types/Types.ts
src/features/user/pages/MemberPage.tsx
src/features/user/pages/dashboard/components/LatestPostsSection.tsx
src/features/user/pages/dashboard/components/MentionedPostsSection.tsx
src/features/user/pages/dashboard/components/PriorityPostsSection.tsx
src/features/user/pages/dashboard/styled/UserDashboardPage.styled.ts

게시글 수정 버그 수정, UI/UX 개선 및 타입 안정성 보완
- 게시글 수정 시 프로젝트 단계가 누락되던 문제 해결  
- 게시글 수정 시 임시값이 들어가던 로직 제거  
- 파일 모델에 contentType 필드 추가  
- 페이지네이션 10개 단위 이동 버튼 추가  
- any 타입 제거 및 명확한 타입 지정  
- 관리자 권한으로 전체 게시글 삭제 가능하도록 수정  
- 대시보드에서 긴 게시글도 UI가 깨지지 않도록 반응형 CSS 및 길이 제한 적용  
- 게시글 생성/수정 모달 외부 클릭 시 닫히지 않도록 UX 개선 (ESC는 유지)  
- 게시글 삭제 시 관리자 문의를 유도하는 메시지를 알림창에 추가
- Close #208 
- See also #

[Feature] 이슈테스트 이후 발견된 버그 수정

---

src/features/admin/pages/DashboardPage.tsx
src/features/company/components/CompanyDetailModal/CompanyDetailModal.tsx
src/features/user/components/MemberDetailModal/MemberDetailModal.tsx

대시보드 api 재연동
백엔드 api 수정에 따른 대시보드 api 재연동 및 그래프 호버기능 추가
- Close #210 
로컬 테스트 정상 작동 확인

[Hotfix] 대시보드 api 재연동

---

src/features/admin/components/ActivityLogDetailModal.tsx
src/features/admin/pages/ActivityLogPage.tsx
src/features/admin/services/activityLogService.ts
src/features/project/pages/ProjectListPage.tsx

프로젝트 및 회사 복구 기능에 대한 API 연동 완료
- 프로젝트 복구 API 연동 
- 회사 복구 버튼 기능과 API 연동 완료
- 복구 요청 시 상태 갱신 및 프론트엔드 연계 확인
- Close #241
- Postman 및 FE 연동 테스트로 복구 요청 정상 처리 확인

[Feature] 프로젝트 및 회사 복구 기능에 대한 API 연동 

---

src/features/company/components/CompanyFilterBar.tsx
src/features/company/pages/CompanyPage.tsx
src/features/inquiry/pages/InquiryDetailPage.tsx

문의사항 FE 수정
content가 한 줄로만 입력되던 현상 수정
시간대 변경은 배포서버 타임존 이슈 해결로 자동해결
- Close #216 
로컬 테스트 정상 동작 확인

[Hotfix] 문의사항 FE 수정

---

src/features/admin/components/ActivityLogDetailModal.tsx
src/features/admin/pages/ActivityLogPage.tsx
src/features/admin/services/activityLogService.ts
src/features/admin/types/activityLog.ts
src/features/board/components/Post/components/DetailModal/PostHeader.tsx
src/features/board/components/Post/components/DetailModal/ProjectPostDetailModal.tsx
src/features/board/components/Question/components/QuestionAnswerModal/components/PostInfo.tsx
src/features/board/components/Question/components/QuestionAnswerModal/components/QuestionItem.tsx
src/features/user/pages/profile/UserProfilePage.tsx
src/utils/dateUtils.ts

timezone 수정에 맞게 +9h를 삭제
DomainType enum 변경
timezone 수정에 맞게 +9h를 삭제
DomainType enum 변경
- Close #
- See also #

[Hotfix] timezone 수정에 맞게 +9h를 삭제, DomainType enum 변경

---

src/features/project/components/CompanyMemberSelectModal.tsx
src/features/project/components/Progress/StepOrderModal.tsx

[Feature] 회사별 회원 수 표시

---

src/App.css
src/features/admin/pages/DashboardPage.tsx
src/features/company/components/CompanyEditModal/CompanyEditModal.tsx
src/features/company/components/CompanyRegisterModal/CompanyRegisterModal.tsx
src/features/company/pages/CompanyPage.tsx
src/features/inquiry/components/InquiryRegisterModal/InquiryRegisterModal.tsx
src/features/inquiry/pages/InquiryDetailPage.tsx
src/features/user/components/MemberEditModal/MemberEditModal.tsx
src/features/user/components/MemberRegisterModal/MemberRegisterModal.tsx
src/features/user/pages/MemberPage.tsx

각종 입력 제한 두기
MaxLength 수정
- Close #227 
로컬 환경 정상 동작 확인

[Hotfix] 각종 입력 제한 두기
